# Generated by Django 5.2.8 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='name_ar',
        ),
        migrations.AddField(
            model_name='tour',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Short Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_pt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Short Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)'),
        ),
    ]
