# Generated by Django 5.2.8 on 2025-12-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_delete_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, help_text='When the discount offer ends', null=True, verbose_name='Discount End Date'),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, help_text='When the discount offer starts', null=True, verbose_name='Discount Start Date'),
        ),
    ]
