# Generated by Django 5.2.8 on 2025-12-23 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_add_discount_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyBookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Early Booking Offer', max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (Arabic)')),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('subtitle_ar', models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Arabic)')),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage (1-70%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)])),
                ('offer_start_date', models.DateTimeField(help_text='When this early booking offer becomes available')),
                ('offer_end_date', models.DateTimeField(help_text='Deadline for early booking (countdown timer ends here)')),
                ('travel_start_date', models.DateField(help_text='Earliest travel date for this offer')),
                ('travel_end_date', models.DateField(help_text='Latest travel date for this offer')),
                ('min_days_advance', models.PositiveIntegerField(default=90, help_text='Minimum days before travel date to qualify (e.g., 90 = must book 3 months ahead)')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefits, e.g., ["Lower prices", "Better room selection", "Flexible dates"]')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions for this offer')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy for early bookings')),
                ('badge_text', models.CharField(default='Early Bird', help_text='Badge text shown on tour cards', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='offers/early_booking/')),
                ('background_color', models.CharField(default='#2563eb', help_text='Hex color for offer background', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tours', models.ManyToManyField(blank=True, help_text='Select tours included in this early booking offer', related_name='early_booking_offers', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Early Booking Offer',
                'verbose_name_plural': 'Early Booking Offers',
                'ordering': ['-is_featured', 'sort_order', '-created_at'],
            },
        ),
    ]
