# Generated by Django 5.0.1 on 2025-12-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_earlybookingoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_multi_destination',
            field=models.BooleanField(default=False, help_text='Multi-country tour (e.g., Egypt & Jordan, Egypt & Dubai)'),
        ),
    ]
