# Generated by Django 5.0.1 on 2025-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_is_multi_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earlybookingoffer',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='earlybookingoffer',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='earlybookingoffer',
            name='title_ar',
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='badge_text_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Badge Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='badge_text_pt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Badge Text (Portuguese)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='cancellation_policy_es',
            field=models.TextField(blank=True, verbose_name='Cancellation Policy (Spanish)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='cancellation_policy_pt',
            field=models.TextField(blank=True, verbose_name='Cancellation Policy (Portuguese)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='subtitle_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Spanish)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='subtitle_pt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Portuguese)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='terms_conditions_es',
            field=models.TextField(blank=True, verbose_name='Terms & Conditions (Spanish)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='terms_conditions_pt',
            field=models.TextField(blank=True, verbose_name='Terms & Conditions (Portuguese)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='earlybookingoffer',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourfaq',
            name='answer_es',
            field=models.TextField(blank=True, verbose_name='Answer (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourfaq',
            name='answer_pt',
            field=models.TextField(blank=True, verbose_name='Answer (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourfaq',
            name='question_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Question (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourfaq',
            name='question_pt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Question (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourhighlight',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourhighlight',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourhighlight',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourhighlight',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='alt_text_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='alt_text_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='caption_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourinclusion',
            name='item_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourinclusion',
            name='item_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item (Portuguese)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='accommodation_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Accommodation (Spanish)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='accommodation_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Accommodation (Portuguese)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='locations_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Locations (Spanish)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='locations_pt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Locations (Portuguese)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='meals_included_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meals Included (Spanish)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='meals_included_pt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meals Included (Portuguese)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='season_name_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Season Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='season_name_pt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Season Name (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tourtype',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='tourtype',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
    ]
