# Generated by Django 5.2.8 on 2026-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_add_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_description_pt',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (Spanish)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_keywords_pt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_title_pt',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title (Portuguese)'),
        ),
    ]
