# Generated by Django 4.2.27 on 2026-02-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tour_meta_description_es_tour_meta_description_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpricing',
            name='season_name',
            field=models.CharField(choices=[('Low Season', 'Low Season'), ('Normal Season', 'Normal Season'), ('High Season', 'High Season'), ('Peak Season', 'Peak Season')], default='Low Season', max_length=50),
        ),
    ]
