# Generated by Django 5.0.1 on 2026-04-20 10:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tourpricing_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='tourhighlight',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='tourhighlight',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tourhighlight',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='touritinerary',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='touritinerary',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='touritinerary',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
    ]
