# Generated by Django 5.0.1 on 2026-04-21 12:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_tour_description_alter_tour_description_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='cancellation_policy',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Cancellation policy for early bookings'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='cancellation_policy_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Cancellation Policy (Spanish)'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='cancellation_policy_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Cancellation Policy (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='terms_conditions',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Terms and conditions for this offer'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='terms_conditions_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Terms & Conditions (Spanish)'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='terms_conditions_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Terms & Conditions (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='tourfaq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='tourfaq',
            name='answer_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Answer (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tourfaq',
            name='answer_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Answer (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
    ]
