# Generated by Django 5.0.1 on 2026-04-21 12:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_earlybookingoffer_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='subtitle_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Subtitle (Spanish)'),
        ),
        migrations.AlterField(
            model_name='earlybookingoffer',
            name='subtitle_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Subtitle (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='short_description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Short Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='short_description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Short Description (Portuguese)'),
        ),
    ]
