# Generated by Django 5.0.1 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0013_alter_earlybookingoffer_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_alt_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_alt_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Caption"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_caption_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Caption (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_caption_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Caption (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_description",
            field=models.TextField(blank=True, verbose_name="Banner Description"),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_description_es",
            field=models.TextField(
                blank=True, verbose_name="Banner Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_description_pt",
            field=models.TextField(
                blank=True, verbose_name="Banner Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Title"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="earlybookingoffer",
            name="banner_image_title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Banner Title (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_alt_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_alt_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_caption_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_caption_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_alt_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_alt_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_caption_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_caption_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="image_title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_alt_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_alt_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_caption_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_caption_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="touritinerary",
            name="image_title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
    ]
