# Generated by Django 4.2.27 on 2026-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_add_image_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinclusion',
            name='item',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tourinclusion',
            name='item_es',
            field=models.CharField(blank=True, max_length=500, verbose_name='Item (Spanish)'),
        ),
        migrations.AlterField(
            model_name='tourinclusion',
            name='item_pt',
            field=models.CharField(blank=True, max_length=500, verbose_name='Item (Portuguese)'),
        ),
    ]
