# Generated by Django 5.2.8 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ar',
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.TextField(blank=True, verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_pt',
            field=models.TextField(blank=True, verbose_name='Content (Portuguese)'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_es',
            field=models.TextField(blank=True, max_length=300, verbose_name='Excerpt (Spanish)'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_pt',
            field=models.TextField(blank=True, max_length=300, verbose_name='Excerpt (Portuguese)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Portuguese)'),
        ),
    ]
