# Generated by Django 5.0.1 on 2025-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_name_ar_remove_post_content_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_alt_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_alt_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Portuguese)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_es',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_pt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name (Portuguese)'),
        ),
    ]
