# Generated by Django 5.0.1 on 2026-04-20 10:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content (Spanish)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content (Portuguese)'),
        ),
    ]
