# Generated by Django 5.0.1 on 2026-04-21 12:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content_alter_post_content_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
    ]
