# Generated by Django 5.0.1 on 2026-04-21 12:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Excerpt (Spanish)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Excerpt (Portuguese)'),
        ),
    ]
