# Generated by Django 5.2.8 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_ar',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ar',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(blank=True, verbose_name='Answer (Spanish)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pt',
            field=models.TextField(blank=True, verbose_name='Answer (Portuguese)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='Question (Spanish)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Question (Portuguese)'),
        ),
    ]
