# Generated by Django 5.2.8 on 2025-12-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_faq_answer_ar_remove_faq_question_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='e.g., 25+, 50,000+, 6', max_length=50)),
                ('label', models.CharField(help_text='e.g., Years Experience', max_length=100)),
                ('label_es', models.CharField(blank=True, max_length=100, verbose_name='Label (Spanish)')),
                ('label_pt', models.CharField(blank=True, max_length=100, verbose_name='Label (Portuguese)')),
                ('icon', models.CharField(choices=[('clock', 'Clock - Years Experience'), ('users', 'Users - Happy Travelers'), ('map-pin', 'Map Pin - Local Offices'), ('globe', 'Globe - Countries Partners'), ('award', 'Award - Awards'), ('star', 'Star - Rating'), ('heart', 'Heart - Satisfaction'), ('shield', 'Shield - Certified')], default='star', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['sort_order'],
            },
        ),
    ]
