# Generated by Django 5.0.1 on 2025-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_newsletter_double_optin'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='address_es',
            field=models.TextField(blank=True, verbose_name='Address (Spanish)'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_pt',
            field=models.TextField(blank=True, verbose_name='Address (Portuguese)'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='City (Spanish)'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_pt',
            field=models.CharField(blank=True, max_length=100, verbose_name='City (Portuguese)'),
        ),
        migrations.AddField(
            model_name='office',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='office',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)'),
        ),
        migrations.AddField(
            model_name='office',
            name='working_hours_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Working Hours (Spanish)'),
        ),
        migrations.AddField(
            model_name='office',
            name='working_hours_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Working Hours (Portuguese)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='description_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='description_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description (Portuguese)'),
        ),
    ]
