# Generated by Django 4.2.27 on 2026-02-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_add_newsletter_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
