# Generated by Django 5.0.1 on 2026-04-21 12:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_inquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Answer (Spanish)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Answer (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Email content (HTML supported)'),
        ),
    ]
