# Generated by Django 5.2.8 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', max_length=5),
        ),
    ]
