# Generated by Django 5.2.8 on 2025-12-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_preferred_language'),
        ('users', '0002_delete_wishlist'),
    ]

    operations = [
    ]
