# Generated by Django 5.2.8 on 2025-12-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_description_ar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
