# Generated by Django 5.0.1 on 2025-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_delete_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='alt_text_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='alt_text_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (Spanish)'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='caption_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (Portuguese)'),
        ),
    ]
