# Generated by Django 5.2.8 on 2026-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_add_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit_es',
            field=models.TextField(blank=True, verbose_name='Best Time to Visit (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit_pt',
            field=models.TextField(blank=True, verbose_name='Best Time to Visit (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='climate_info_es',
            field=models.TextField(blank=True, verbose_name='Climate Info (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='climate_info_pt',
            field=models.TextField(blank=True, verbose_name='Climate Info (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='getting_there_es',
            field=models.TextField(blank=True, verbose_name='Getting There (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='getting_there_pt',
            field=models.TextField(blank=True, verbose_name='Getting There (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_description_pt',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_keywords_pt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_title_pt',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title (Portuguese)'),
        ),
    ]
