# Generated by Django 4.2.27 on 2026-01-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_destination_best_time_to_visit_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='video_url',
        ),
    ]
