# Generated by Django 5.0.1 on 2026-04-20 10:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_remove_banner_and_video_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
    ]
