# Generated by Django 5.0.1 on 2026-04-21 12:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_alter_destination_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_time_to_visit',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_time_to_visit_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Best Time to Visit (Spanish)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_time_to_visit_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Best Time to Visit (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate_info_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Climate Info (Spanish)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate_info_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Climate Info (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='getting_there',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='getting_there_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Getting There (Spanish)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='getting_there_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Getting There (Portuguese)'),
        ),
    ]
