# Generated by Django 5.0.1 on 2026-04-21 12:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tagline',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tagline_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Tagline (Spanish)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tagline_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Tagline (Portuguese)'),
        ),
    ]
