# Generated by Django 5.0.1 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0009_alter_destination_tagline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_alt_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_alt_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_caption_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_caption_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="image_title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_alt_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_alt_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_caption_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_caption_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Caption (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image_title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="destinationimage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="destinationimage",
            name="description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="destinationimage",
            name="description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="destinationimage",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="destinationimage",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="destinationimage",
            name="title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
    ]
