# Generated by Django 5.2.8 on 2026-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_add_image_seo_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='meta_keywords_es',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='meta_keywords_pt',
        ),
        migrations.AddField(
            model_name='destination',
            name='focus_keyphrase',
            field=models.CharField(blank=True, help_text='Main keyword to rank for. Place in H1, URL, Meta Title, first 100 words.', max_length=255, verbose_name='Focus Key Phrase'),
        ),
        migrations.AddField(
            model_name='destination',
            name='focus_keyphrase_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Focus Key Phrase (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='focus_keyphrase_pt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Focus Key Phrase (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='long_tail_phrases',
            field=models.TextField(blank=True, help_text='Specific search queries, one per line. E.g.: How much does the Nile Splendor 8 day tour cost?', verbose_name='Long Tail Phrases'),
        ),
        migrations.AddField(
            model_name='destination',
            name='long_tail_phrases_es',
            field=models.TextField(blank=True, verbose_name='Long Tail Phrases (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='long_tail_phrases_pt',
            field=models.TextField(blank=True, verbose_name='Long Tail Phrases (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='lsi_keywords',
            field=models.TextField(blank=True, help_text='Synonyms and variations, comma-separated. E.g.: Egypt package, Nile trip, Cairo Luxor tour', verbose_name='LSI Keywords'),
        ),
        migrations.AddField(
            model_name='destination',
            name='lsi_keywords_es',
            field=models.TextField(blank=True, verbose_name='LSI Keywords (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='lsi_keywords_pt',
            field=models.TextField(blank=True, verbose_name='LSI Keywords (Portuguese)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='semantic_keywords',
            field=models.TextField(blank=True, help_text='5-10 related terms, comma-separated. E.g.: Valley of the Kings, Karnak Temple, 5 star Nile cruise', verbose_name='Semantic Keywords'),
        ),
        migrations.AddField(
            model_name='destination',
            name='semantic_keywords_es',
            field=models.TextField(blank=True, verbose_name='Semantic Keywords (Spanish)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='semantic_keywords_pt',
            field=models.TextField(blank=True, verbose_name='Semantic Keywords (Portuguese)'),
        ),
    ]
