# Generated by Django 5.0.1 on 2025-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_es',
            field=models.TextField(blank=True, verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_pt',
            field=models.TextField(blank=True, verbose_name='Content (Portuguese)'),
        ),
        migrations.AddField(
            model_name='review',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='review',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (Spanish)'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='caption_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (Portuguese)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_es',
            field=models.TextField(blank=True, verbose_name='Quote (Spanish)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_pt',
            field=models.TextField(blank=True, verbose_name='Quote (Portuguese)'),
        ),
    ]
