# Generated by Django 5.0.1 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_add_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alt Text"),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="alt_text_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alt Text (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="alt_text_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alt Text (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Image Description"),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="description_es",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="description_pt",
            field=models.TextField(
                blank=True, verbose_name="Image Description (Portuguese)"
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title"
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Spanish)"
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="title_pt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Title (Portuguese)"
            ),
        ),
    ]
